apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: prod
  labels:
    app.kubernetes.io/name: nginx
spec:
  containers:
  - name: nginx
    image: ubuntu/nginx:1.28-26.04_edge
    ports:
      - containerPort: 80
